import sys
import warnings

# Ingore error when integrate PyQt5 and pywinauto
warnings.simplefilter('ignore', UserWarning)
sys.coinit_flags = 2

from PyQt5 import uic
from PyQt5.QtWidgets import QApplication, QMainWindow

from app.app_ui import Ui_MainWindow
from app.automation.auto import start

# Ui_MainWindow class generated by PyQt5 during execution
# to manually generate: pyuic5 app/app.ui > app/app_ui.py
UI: Ui_MainWindow = uic.loadUiType('app/app.ui')[0]


class MainApp(QMainWindow, UI):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)
        self.handle_buttons()

    def handle_buttons(self):
        self.button_40.clicked.connect(lambda: self.set_value(40))
        self.button_60.clicked.connect(lambda: self.set_value(60))
        self.button_100.clicked.connect(lambda: self.set_value(100))

        self.button_cancel.clicked.connect(self.close)
        self.button_ok.clicked.connect(self.set_brightness)

    def set_value(self, value):
        self.value_box.setValue(value)

    def set_brightness(self):
        self.showMinimized()
        start(self.value_box.value())
        self.showNormal()


def main():
    app = QApplication([])
    window = MainApp()  # Union[QMainWindow, Ui_MainWindow]
    window.show()

    app.exec_()


if __name__ == '__main__':
    main()
